### PR TITLE
dibs: I will implement exercise "difference of squares"

### PR DESCRIPTION
**Pull request by zgavin1**
WIP: dibs: I will implement exercise "difference of squares"

### CODE REVIEW

**Comment by masters3d** [comment]
You can get the test suit from the es6 track.

**Comment by zgavin1** [comment]
@masters3d Whoops - got the test suite from JavaScript.

**Comment by masters3d** [comment]
LGTM. let me know when it is not WIP

**Comment by zgavin1** [comment]
@masters3d Good to go! The exercism.io team has made this super easy to contribute to! Thanks 👍

**Pull request merged**
